docs/interface.md
This summarizes the security issues that we have identified in discussions with the Chrome security team.
=> interface doc: Added Security Considerations section.

docs/interface.md
=> Require user gesture

docs/interface.md, index.html, tidyconfig.txt
Readable copy of this draft on [RawGit](https://rawgit.com/mgiuca/web-share/spec/index.html).
Marcos, perhaps you could take a look at this draft, when you have time. I've had Shane Stephens at Google take a first pass over it and made some changes he suggested.
=> Adds Web Share spec draft

index.html
=> Share method: Remove the ability for the share target to decline.

.pr-preview.json
Apparently allows pull request previews and HTML diffs.
=> Added .pr-preview.json.

index.html
***
<a href="https://s3.amazonaws.com/pr-preview/WICG/web-share/pull/58.html" title="Last updated on Nov 27, 2017, 4:39 AM GMT">Preview</a> | <a href="https://s3.amazonaws.com/pr-preview/WICG/web-share/d39a1a7...c577ae2.html" title="Last updated on Nov 27, 2017, 4:39 AM GMT">Diff</a>
=> Add link to test suite

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/pull/56.html" title="Last updated on Feb 12, 2018, 3:05 AM GMT (16f99af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/56/d39a1a7...16f99af.html" title="Last updated on Feb 12, 2018, 3:05 AM GMT (16f99af)">Diff</a>
=> Modernize example and show that it throws

docs/explainer.md, index.html
We now say
"Data was shared successfully"
resolves #62
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/74.html" title="Last updated on Mar 15, 2018, 12:38 AM GMT (286c673)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/74/9c37cf9...ewilligers:286c673.html" title="Last updated on Mar 15, 2018, 12:38 AM GMT (286c673)">Diff</a>
=> Update success message in example

.pr-preview.json, README.md, level-2/index.html
Level 2 will add `canShare()` and support for file sharing.
=> [web-share] Introduce Level 2 Spec

level-2/index.html
level-2/index.html was based on an old version of index.html
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/80.html" title="Last updated on Oct 10, 2018, 12:18 AM GMT (9a1903b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/80/76d365d...ewilligers:9a1903b.html" title="Last updated on Oct 10, 2018, 12:18 AM GMT (9a1903b)">Diff</a>
=> Rebase level-2/index.html

level-2/index.html
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/89.html" title="Last updated on Feb 7, 2019, 5:17 AM UTC (3fe3324)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/89/a29dc9f...ewilligers:3fe3324.html" title="Last updated on Feb 7, 2019, 5:17 AM UTC (3fe3324)">Diff</a>
=> Avoid executing shared files

level-2/index.html
resolves #90
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/91.html" title="Last updated on Feb 25, 2019, 11:45 PM UTC (03b9002)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/91/d18ffab...ewilligers:03b9002.html" title="Last updated on Feb 25, 2019, 11:45 PM UTC (03b9002)">Diff</a>
=> When blocking file types, reject with NotAllowedError.

README.md
Update README with a link to chromestatus.
=> Level 2 is being implemented in Chrome

level-2/index.html
This spec has been discussed with TAG and has an implementation.
=> Remove 'early draft' wording

demos/share.html
This feature is about to ship in Chrome 75 beta, which is expected to go out late next week. I'm working on an article about it for https://developers.google.com/web/updates. I'd really appreciate it if someone could jump on this quickly.
Thanks,
Joe
=> Make web share demo a little more mobile friendly.

demos/index.html, demos/share-files.html, demos/share.html
Because this will very soon [be in Chrome beta](https://www.chromestatus.com/feature/4777349178458112).
=> Add a demo for file sharing.

index.html
=> chore(index): Migration to W3C

level-2/index.html
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/web-share/pull/117.html" title="Last updated on Aug 10, 2019, 6:31 AM UTC (2dda98e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/117/4e61076...saschanaz:2dda98e.html" title="Last updated on Aug 10, 2019, 6:31 AM UTC (2dda98e)">Diff</a>
=> Fix WebIDL validation error

index.html
Fixes a few ReSpec issues and gives algorithm `var`s a type.
=> editorial: ReSpec fixes + enhancements

README.md, index.html
Dropped level as per #107. The rest of the document looks good. 
We may want to include something in the status about files and feature detection, just to give anyone reviewing the spec that we plan to add that (with links to the pull requests).
=> Editorial: drop levels + small fixes

index.html
=> Added Eric Willigers as co-editor.

index.html
=> editorial: Link `this` to Web IDL

index.html
Add non-normative section reminding implementors to follow
OS level accessibility guidelines.
Closes #145
=> Accessibility considerations

index.html
Tiny fix for a ReSpec error...
=> chore: use ReSpec IDL syntax

index.html
=> Editorial: s/feature-policy/permissions-policy

index.html
=> User a sequence for files

index.html
Closes #188 
(Match windows API)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/209.html" title="Last updated on Aug 13, 2021, 4:48 AM UTC (d1b2e33)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/209/828058d...d1b2e33.html" title="Last updated on Aug 13, 2021, 4:48 AM UTC (d1b2e33)">Diff</a>
=> Resolve promise after OS hand-off

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/210.html" title="Last updated on Aug 17, 2021, 8:32 PM UTC (d7552d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/210/230ec6a...d7552d7.html" title="Last updated on Aug 17, 2021, 8:32 PM UTC (d7552d7)">Diff</a>
=> Editorial: describe permissions policy reliance in priv/sec section

index.html
Closes #223
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/243.html" title="Last updated on Jun 7, 2022, 8:50 AM UTC (b295ed9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/243/c628c47...b295ed9.html" title="Last updated on Jun 7, 2022, 8:50 AM UTC (b295ed9)">Diff</a>
=> Editorial: address security review feedback

index.html
Closes #217
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/242.html" title="Last updated on Jun 8, 2022, 12:11 AM UTC (7ad1648)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/242/ea084c0...7ad1648.html" title="Last updated on Jun 8, 2022, 12:11 AM UTC (7ad1648)">Diff</a>
=> Editorial: clarify potentially hostile share

index.html
closes #64
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/240.html" title="Last updated on Jul 7, 2022, 5:15 AM UTC (93ed578)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/240/3f97331...93ed578.html" title="Last updated on Jul 7, 2022, 5:15 AM UTC (93ed578)">Diff</a>
=> Editorial: move UI suggestion to Priv/Sec section

index.html
Closes #250
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/251.html" title="Last updated on Sep 21, 2022, 12:57 AM UTC (3309ea1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/251/d2110af...3309ea1.html" title="Last updated on Sep 21, 2022, 12:57 AM UTC (3309ea1)">Diff</a>
=> Editorial: use this' relevant global object

index.html
Closes #169
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/252.html" title="Last updated on Nov 3, 2022, 3:18 AM UTC (9e2fccb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/252/3d2ee38...9e2fccb.html" title="Last updated on Nov 3, 2022, 3:18 AM UTC (9e2fccb)">Diff</a>
=> Editorial: remove feature at risk for Permissions Policy

index.html
Non-normative.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/257.html" title="Last updated on Dec 15, 2022, 2:32 PM UTC (1cbbeea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/257/9226ea5...1cbbeea.html" title="Last updated on Dec 15, 2022, 2:32 PM UTC (1cbbeea)">Diff</a>
=> Fix capitalisation of heading

index.html
If you don't have URL present, there's no need to deal with base.
Closes #259
Each implementation of the current algorithm meets the same necessary conditions, however the code is written.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 23, 2023, 3:43 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fchaals%2Fweb-share%2F88cd09c590002f3dbdc004487fb8e3fe53bb7ea2%2Findex.html%3FisPreview%3 …
=> Editorial: streamline main algorithm

index.html
Closes #266
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/268.html" title="Last updated on Jan 24, 2023, 1:06 AM UTC (a2070e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/268/d5fbdfa...a2070e7.html" title="Last updated on Jan 24, 2023, 1:06 AM UTC (a2070e7)">Diff</a>
=> Editorial: switch to 'terminate this algorithm'

index.html
Closes #265
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/269.html" title="Last updated on Jan 24, 2023, 1:09 AM UTC (032a4e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/269/5c9977c...032a4e5.html" title="Last updated on Jan 24, 2023, 1:09 AM UTC (032a4e5)">Diff</a>
=> Editorial: thank wide review groups in acknowledgements

imp-report/index.html, index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/274.html" title="Last updated on Feb 23, 2023, 5:58 AM UTC (0d36f7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/274/35980bb...0d36f7f.html" title="Last updated on Feb 23, 2023, 5:58 AM UTC (0d36f7f)">Diff</a>
=> Editorial: add static implementation report

index.html
CC @tantek
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/273.html" title="Last updated on Mar 1, 2023, 1:08 AM UTC (758b0f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/273/0a7a70c...758b0f7.html" title="Last updated on Mar 1, 2023, 1:08 AM UTC (758b0f7)">Diff</a>
=> Editorial: note canShare is not future compatible

index.html
Closes #281
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/283.html" title="Last updated on Jun 6, 2024, 8:33 AM UTC (2ff1da4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/283/0b15b86...2ff1da4.html" title="Last updated on Jun 6, 2024, 8:33 AM UTC (2ff1da4)">Diff</a>
=> Editorial: fix typo in example
