w3c/web-share

docs/explainer.md, docs/interface.md
=> Removed navigator.canShare.

docs/interface.md
Fixes https://github.com/WICG/web-share/issues/19
=> Make ShareData members non-nullable

index.html
This also uses the github key rather than manually (and differently) generating the links that including it generates.
=> Correct metadata for being a WICG document.

index.html
Added a security consideration that implementations should be careful
about exposing this information.
This isn't a technical change, but changes a weak recommendation *to*
differentiate error cases to a weak recommendation *against* it.
Closes #29.
=> Removed note about distinguishing between different error cases.

index.html
This is consistent with the current implementation in Chrome.
Closes #34.
***
[Preview](https://s3.amazonaws.com/pr-preview/mgiuca/web-share/spec-url-relative.html) | [Diff](https://s3.amazonaws.com/pr-preview/WICG/web-share/dac4c21...mgiuca:69f29d6.html)
=> spec: share now resolves url relative to the document base URL.

index.html
Fixes a spec bug where a non-existent URL would be parsed.
Closes #39.
***
[Preview](https://s3.amazonaws.com/pr-preview/mgiuca/web-share/spec-check-missing-url.html) | [Diff](https://s3.amazonaws.com/pr-preview/WICG/web-share/0be490e...mgiuca:3386eb5.html)
=> spec: Check whether url is present before processing it.

index.html
Closes #36, #37, #40 and #43.
***
[Preview](https://s3.amazonaws.com/pr-preview/mgiuca/web-share/spec-cleanup.html) | [Diff](https://s3.amazonaws.com/pr-preview/WICG/web-share/857fe5c...mgiuca:b658e25.html)
=> Miscellaneous spec cleanup (no normative changes)

index.html
Minor breaking change, as discussed on #45. Closes #45.
***
[Preview](https://s3.amazonaws.com/pr-preview/mgiuca/web-share/gesture-error-type.html) | [Diff](https://s3.amazonaws.com/pr-preview/WICG/web-share/5c2c8bb...mgiuca:eda2322.html)
=> spec: Changed user gesture error from SecurityError to NotAllowedError.

index.html
This makes sharing the empty dictionary, or a dictionary with only unrecognised fields, a programmer error, and is designed to aid in future extensions (since if new fields are added, it will be a TypeError to exclusively use them without feature detection).
Also adds an appendix discussing extending the spec in the future.
Closes #48.
***
[Preview](https://s3.amazonaws.com/pr-preview/mgiuca/web-share/empty-dict-error.html) | [Diff](https://s3.amazonaws.com/pr-preview/WICG/web-share/5c2c8bb...mgiuca:0c7a74d.html)
=> spec: Throw a TypeError if all fields are missing.

index.html
This has no behavioural change, as passing an empty dictionary is a
TypeError. But it is required by the WebIDL spec.
Closes #47.
***
[Preview](https://s3.amazonaws.com/pr-preview/mgiuca/web-share/optional-argument.html) | [Diff](https://s3.amazonaws.com/pr-preview/WICG/web-share/4e65307...mgiuca:f421675.html)
=> spec: Make ShareData argument optional.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/pull/54.html" title="Last updated on Nov 29, 2017, 3:11 AM GMT">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/d39a1a7...9c2b429.html" title="Last updated on Nov 29, 2017, 3:11 AM GMT">Diff</a>
=> fix: ReSpec link warnings

index.html
We now consistently say that .share() will return a rejected
promise, instead of sometimes saying that it throws.
resolves #57
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/71.html" title="Last updated on Feb 19, 2018, 5:38 AM GMT (6ae2c73)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/71/f982ffb...ewilligers:6ae2c73.html" title="Last updated on Feb 19, 2018, 5:38 AM GMT (6ae2c73)">Diff</a>
=> Return rejected promise; don't throw

index.html
Consistently use the WebIDL terminology 'member' instead of sometimes
using 'member' and sometimes using 'field'.
resolves #55
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/70.html" title="Last updated on Feb 16, 2018, 4:49 AM GMT (3996335)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/70/f982ffb...ewilligers:3996335.html" title="Last updated on Feb 16, 2018, 4:49 AM GMT (3996335)">Diff</a>
=> member not field

level-2/index.html
Add a files member to Web Share dictionary.
Add canShare() so authors can determine if an implementation supports sharing a given ShareData dictionary. In particular, this allows authors to determine if an implementation supports sharing files.
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/78.html" title="Last updated on Oct 10, 2018, 12:25 AM GMT (18e0eff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/78/05a87d5...ewilligers:18e0eff.html" title="Last updated on Oct 10, 2018, 12:25 AM GMT (18e0eff)">Diff</a>
=> Sharing files

level-2/index.html
FileList is discouraged in new standards, and cannot be constructed
by script. We use FrozenArray of File instead.
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/84.html" title="Last updated on Nov 27, 2018, 2:25 AM GMT (ca6c29f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/84/fb374da...ewilligers:ca6c29f.html" title="Last updated on Nov 27, 2018, 2:25 AM GMT (ca6c29f)">Diff</a>
=> Use FrozenArray, not FileList

level-2/index.html
For sites that wish to display a message when the
share dialog is presented, we add a new ShareOptions
dictionary.
This allows for additional options that may be needed in future,
without long method parameter lists.
Note that support for the 'message' option (and likely future
options) is not feature detectable.
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/85.html" title="Last updated on Dec 21, 2018, 4:17 AM UTC (4d026ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/85/d9d43d7...ewilligers:4d026ec.html" title="Last updated on Dec 21, 2018, 4:17 AM UTC (4d026ec)">Diff</a>
=> Optional message to display when sharing

level-2/index.html
This reverts commit 2edec41ee77d9562edb7c4b212d6a2618ce9a7df.
There are security concerns about showing author-supplied messages
as part of the browser UI.
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/87.html" title="Last updated on Jan 15, 2019, 5:26 AM UTC (4ff8a74)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/87/2edec41...ewilligers:4ff8a74.html" title="Last updated on Jan 15, 2019, 5:26 AM UTC (4ff8a74)">Diff</a>
=> Revert "Optional message to display when sharing (#85)"

level-2/index.html
navigator.share({}) already rejects with TypeError.
navigator.share({files: []}) now also rejects.
This came up during implementation
https://chromium-review.googlesource.com/c/chromium/src/+/1351340/2/third_party/blink/renderer/modules/webshare/navigator_share.cc#44
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/86.html" title="Last updated on Jan 18, 2019, 2:05 AM UTC (e6cf286)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/86/3510c0e...ewilligers:e6cf286.html" title="Last updated on Jan 18, 2019, 2:05 AM UTC (e6cf286)">Diff</a>
=> Don't share if files is empty, with other fields absent

level-2/index.html
We have the following changes since Level 1:
-    The feature detection method canShare() has been added.
-    The ShareData dictionary now has a files member for sharing files.
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/88.html" title="Last updated on Jan 18, 2019, 2:54 AM UTC (ad08c95)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/88/7476c3a...ewilligers:ad08c95.html" title="Last updated on Jan 18, 2019, 2:54 AM UTC (ad08c95)">Diff</a>
=> Add Changes Appendex

level-2/index.html
Similiar to
https://github.com/WICG/web-share/pull/92
but skipping caniuse for now.
Requested a caniuse entry for Level 2:-
https://github.com/Fyrd/caniuse/issues/4798
***
<a href="https://pr-preview.s3.amazonaws.com/ewilligers/web-share/pull/93.html" title="Last updated on Mar 6, 2019, 2:46 AM UTC (62db3af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-share/93/9b5d48d...ewilligers:62db3af.html" title="Last updated on Mar 6, 2019, 2:46 AM UTC (62db3af)">Diff</a>
=> chore: fix ReSpec warnings in Level 2

demos/share-files.html, demos/share.html
As noticed during review of
https://github.com/WICG/web-share/pull/97
user activation can be considered to last more than 2 seconds,
so wait 6 seconds in testWebShareDelay().
The text regarding the demo descriptions and supported Chrome
versions was swapped between share.html and share-files.html
share-files.html is the new test that uses file sharing.
=> Cleanup demos/share.html

demos/share-files.html, demos/share.html
If people arrive at the demo page via http://, we now
redirect to https instead of immediately reporting that
navigator.share is not supported.
resolves #100
=> Demo now checks for https

index.html
=> fix: default share(data) to empty dictionary

index.html
* fixes #110
* fixes #112 
For discussion... this prevents  #110 (multiple concurrent shares).
=> Introduce [[sharePromise]] internal slot

index.html
Moved the non-normative explanation out of the Examples section into
the Share targets section, and also addded normative directive that user
agents may discard *or combine* members (emphasis on the new text).
Closes #130.
=> Clarify that UAs can concatenate fields like on Android.

index.html
This is refactor to use HTML's new activation model. The api currently uses transient activation.
Details: https://github.com/whatwg/html/issues/5129 
In a new issue, we need to discuss if calling share should "consume" the activation.
Doing so might have the nice effect that we can get rid of the internal slot we added to protect against being able to call `.share()` twice during the same activation phase.
=> Editorial: Use new HTML activation model

index.html
looks like [=dictionary member/present=] is no longer a thing? No defined in WebIDL anymore at least.
=> chore: 'present' xref does not exist

docs/security-privacy-self-review.md
Closes #149
I went through the S&P self review questionnaire and did my best to answer the questions.
=> Initial take on Security/Privacy self-review

index.html
Add a `files` member to ShareData dictionary.
@ericwilligers, I tried to add in what is in level 2 to kick off discussion. 
=> Add the ability to share files

index.html
We use USVString members as they are not allowed to contain
surrogate code points.
closes #152
=> chore: Clarify reason for choosing USVString

index.html
Export 'share target' so it can be referenced from the Share Target spec. 
When we eventually move Share Target to the WebApps WG, it might be preferable for the normative definition of a "share target" to live in the Share Target spec.
=> chore: export 'share target'

index.html
=> BREAKING CHANGE: make share() consume user activation

index.html
=> Introduce "web-share" feature policy

.github/workflows/action.yml
We plan to deprecate [respec-w3c-auto-publish](https://github.com/w3c/respec-w3c-auto-publish) action in favor of a more generic [`spec-prod`](https://github.com/sidvishnoi/spec-prod/) action. The newer action is more consistent and requires fewer inputs.
=> chore(ci): use the spec-prod GitHub action

index.html
=> Reject non-http URLs for url member

index.html
WPT [web-share/share-sharePromise-internal-slot.https.html](https://github.com/web-platform-tests/wpt/commit/785685cf0921672462da96e99e7)
has multiple `navigator.share()` calls within a single
`onclick` handler. This is a good way to test the sharePromise
internal slot, but it was not previously permitted by the spec,
as the first call would consume activation and the later calls
would fail with `NotAllowedError` instead of `InvalidStateError`.
=> Check transient activation after sharePromise

demos/share-files.html, demos/share.html
While the promise has not yet resolved or rejected, we disable
the share button to prevent additional share attempts.
This avoids confusion arising from
[[sharePromise]] internal slot (#113)
=> Demo: Disable buttons during share

CONTRIBUTING.md, README.md, demos/index.html, demos/share-files.html, demos/share.html, docs/explainer.md, docs/interface.md, index.html
Remove references to WICG
Web Share API is now developed in Web Applications Working Group.
Add style guide explaining use of HTML Tidy.
Link to https://caniuse.com/web-share for current
information about implementation support.
=> chore: Remove references to WICG

index.html
Closes #108 
Closes #159 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/177.html" title="Last updated on Aug 18, 2021, 7:12 AM UTC (338d7fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/177/1904b8f...338d7fa.html" title="Last updated on Aug 18, 2021, 7:12 AM UTC (338d7fa)">Diff</a>
=> Add canShare() method

index.html
Closes #218 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/219.html" title="Last updated on Sep 9, 2021, 7:54 PM UTC (6884cce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/219/3bc95bf...6884cce.html" title="Last updated on Sep 9, 2021, 7:54 PM UTC (6884cce)">Diff</a>
=> Handle non-fully-active documents

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/220.html" title="Last updated on Sep 20, 2021, 10:35 PM UTC (9a32b1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/220/94e7883...9a32b1d.html" title="Last updated on Sep 20, 2021, 10:35 PM UTC (9a32b1d)">Diff</a>
=> fix: canShare() return false if not allowed to use

demos/share-files.html
=> Better log messages for canShare

index.html
Closes #235
Editorial fix-up of what we originally intended. Doesn't affect UA behavior is and shouldn't be observable/testable (AFAIK).
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 27, 2022, 7:07 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fweb-share%2Fc1e3ac98a686aa46f3fd9fdb59ba9c6ed871da8a%2Findex.html%3FisPreview%3Dtrue)
```
📡 HTTP Error 404: …
```
=> Editorial: use global task to resolve promises

index.html
Closes #227
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/238.html" title="Last updated on Jun 7, 2022, 1:52 AM UTC (06fa9cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/238/9f9dc92...06fa9cd.html" title="Last updated on Jun 7, 2022, 1:52 AM UTC (06fa9cd)">Diff</a>
=> Editorial: add more examples

index.html
Closes #65
Discussion of relative/absolute URL for the `url` member is covered in the Usage Examples section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/241.html" title="Last updated on Jun 7, 2022, 6:06 AM UTC (e1701f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/241/45508be...e1701f6.html" title="Last updated on Jun 7, 2022, 6:06 AM UTC (e1701f6)">Diff</a>
=> Editorial: cleanup notes

index.html
Closes #61 
In light of #108, I think we should remove this. 
Example of how developers find what is supported was part of #238.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/239.html" title="Last updated on Jul 7, 2022, 5:13 AM UTC (3b15c9d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/239/c33c7af...3b15c9d.html" title="Last updated on Jul 7, 2022, 5:13 AM UTC (3b15c9d)">Diff</a>
=> Editorial: remove Extensibility text

index.html
Closes #187
Closes #186 
Closes #64
As requested by @melanierichards on behalf of PING, I've moved all the security stuff into the appropriate parts of the spec and made them normative.
I left the specific privacy considerations in place, but also made them normative. The consideration that the API doesn't leak the share targets is a statement of fact (i.e., it would be redundant to state it normatively because that's the design of the API already).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/245.html" title="Last updated on Jul 7, 2022, 8:45 AM UTC (c06b399)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/245/d3890d1...c06b399.html" title="Last updated on Jul 7, 2022, 8:45 AM UTC (c06b399)">Diff</a>
=> Editiorial: Move Priv/Sec into normative parts of spec

.github/workflows/auto-publish.yml
Enables publishing as Candidate Recommendation Draft after the we publish CR... which should happen later today.
=> chore: auto-publish as CRD

index.html
Addresses feedback received from:
https://github.com/w3c/transitions/issues/476
@siusin, can you please check it? 🙏
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/256.html" title="Last updated on Dec 12, 2022, 12:53 AM UTC (ed05253)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/256/d5cf6ac...ed05253.html" title="Last updated on Dec 12, 2022, 12:53 AM UTC (ed05253)">Diff</a>
=> Editorial: address Proposed Recommendation Feedback

index.html
The title didn't match what the example does.
using `allow` **enables** rather than **disables** the API in a 3rd-party iframe
Closes #262
Non-normative change (because it's an example).
***
<a href="https://pr-preview.s3.amazonaws.com/chaals/web-share/pull/263.html" title="Last updated on Jan 4, 2023, 6:45 PM UTC (f0b72e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/263/98b6c0f...chaals:f0b72e9.html" title="Last updated on Jan 4, 2023, 6:45 PM UTC (f0b72e9)">Diff</a>
=> Explain example correctly

index.html
Closes #264
@chaals, please take a look. Any suggestions for improving this welcomed!
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/270.html" title="Last updated on Jan 24, 2023, 1:10 AM UTC (48a94cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/270/783e54b...48a94cc.html" title="Last updated on Jan 24, 2023, 1:10 AM UTC (48a94cc)">Diff</a>
=> Editorial: improve a11y guidelines for share sheet

index.html
CC @tantek - to address Formal Objection. 
* Web platform tests - learning the tests as they are, as eventually use agents should support the header. 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/275.html" title="Last updated on Mar 1, 2023, 1:57 AM UTC (4c45203)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/275/7f78426...4c45203.html" title="Last updated on Mar 1, 2023, 1:57 AM UTC (4c45203)">Diff</a>
=> Make Permissions-Policy HTTP header OPTIONAL

index.html
Closes #276
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/277.html" title="Last updated on Apr 11, 2023, 7:03 AM UTC (aa811f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/277/e441b96...aa811f9.html" title="Last updated on Apr 11, 2023, 7:03 AM UTC (aa811f9)">Diff</a>
=> chore: prepare for REC
